### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#1055]
# Release 1.0

I feel that ODL has now come far enough for us to start planning a 1.0 release. This is for several reasons:

* The user-base has started to grow somewhat, and breaking changes etc are starting to become a problem.
* ODL is largely feature complete w.r.t the basic stuff you need for inverse problems.
* A 1.0 release signals that we're in some sense ready to face the world and no longer a small internal project.

### Remaining issues

Before a proper 1.0 release, I personally feel that these issues remain to be solved (i.e. somehow closed)

- [ ] #1017 Figure of Merits
- [ ] #972 Tensorflow
- [ ] #861 Tensor spaces, along with followup issues:
   - [ ] #342 Vector and tensor fields
   - [ ] #731 libgpuarray backend
   - [ ] #908 Representing vector- and tensor-valued functions
   - [ ] #857 Power spaces and tensors
   - [ ] #965 Indexing of multi-dimensional spaces
- [ ] #935 Add OperatorMeta
- [ ] A general cleanup of TODOs

Feel free to add more stuff to this list.

### Release workflow

Since 1.0 is a major release that we'd hope to be stable, I propose that we first update ODL to `1.0.rc1`, where `rc1` means release candidate 1 and work with this for a short while in order to guarantee a good release.

### Breaking changes after 1.0

I propose that we, after 1.0, try to allow at least one minor version between breaking changes, i.e. first add a warning and then later actually remove the feature. For obvious reasons we don't need to religiously follow this, but I feel that it would help more people use ODL.

**Comment by kohr-h** [comment]
> Release workflow
> 
> Since 1.0 is a major release that we'd hope to be stable, I propose that we first update ODL to 1.0.rc1, where rc1 means release candidate 1 and work with this for a short while in order to guarantee a good release.

Sounds good.



> Breaking changes after 1.0
> 
> I propose that we, after 1.0, try to allow at least one minor version between breaking changes, i.e. first add a warning and then later actually remove the feature. For obvious reasons we don't need to religiously follow this, but I feel that it would help more people use ODL.

I agree. At large I'd say that after 1.0 we need a Really Good Reason (TM) for breaking changes, at least in *public* APIs. Here I feel that in general, we could do a better job at differentiating between public and private APIs. For starters, anything that is not part of `__all__` should be considered internal or implementation detail and thus not part of any API guarantee. We could make this more clear by putting underscores before all these guys.

**Comment by kohr-h** [comment]
I've made [a project page](https://github.com/odlgroup/odl/projects/5) to keep track of the status of the issues and PRs. It's a bit easier to keep an overview there.
