### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#1335]
It's been quite a while since the last release, and it seems like still a while to go until 1.0, since there are a bunch of quite big and important changes still to be finalized and merged. See #1055.

So how about we release once before, say 0.9.0, with roughly the current status? I also seem to remember that there were some changes in the `conda build` process that need to be done, and we don't want to screw up 1.0 for that reason.

**Edit:** I'll start with this and maintain a checklist here that reflects the process outlined in [the release documentation](https://odlgroup.github.io/odl/dev/release.html).

- [x] 1. Agree on a release schedule
  - [x] Open an issue on the issue tracker using the title "Release 0.7.0"
  - [x] Discuss and agree on a set of open PRs that should be merged and issues that should be resolved before making a release
- [x] 2. Make sure tests succeed (including large-scale tests) and docs are built properly
  - [x] If anything fails, fix and make PR bevore proceeding (#1426)
  - [x] Python 2.7
  - [x] Python 3.{4,5,6}
  - [x] Windows
- [x] 3. Make a release branch `release-0.7.0` off `master`, on a fork like for any other PR
- [x] 4. Bump the master `branch` to the next development version (here `'1.0.0.dev0'`)
  - [x] `odl/__init__.py`
  - [x] `conda/meta.yaml`
  - [x] Make a PR and merge it
- [x] 5. Compile and publish the release
  - [x] Compile the release notes with user-visible changes
  - [x] Increment the version number to `'0.7.0'` in `odl/__init__.py` and `conda/meta.yaml`
  - [x] Change the `git_rev` field in `conda/meta.yaml` to `'v0.7.0'`
  - ~~Make a PR and fix review comments, using a single commit `REL: bump version to 0.7.0`~~ Done on master
  - [x] Push the release branch to the main repository
  - [x] Draft a new release on GitHub using the the `release-0.7.0` branch and the short summary from the release notes file; add a link to the release notes page
- [x] 6. Create packages for PyPI and Conda
- [x] 7. Test installing the local packages and check them
  - [x] From source
  - [x] From wheel
  - [x] From conda package
- [x] 8. Upload the packages to the official locations
- ~~9. Merge the release branch~~ Not merging

**Comment by adler-j** [comment]
I agree that we should do this, but the version would be 0.7 according to standard numbering.

Do we have a list of things we want done here?

**Comment by kohr-h** [comment]
I'd suggest we only put stuff here that we can fix in relatively short time. Here's a list, feel free to edit:

**PRs**
- [ ] #1321 (practically done)
- [ ] #1307 (also done for all intents and purposes)
- [ ] #1280 (if possible)

The others are more fundamental or need significant work as far as I can judge.

**Open issues**
- [ ] #1312 definitely since it's a new API, last chance to adjust

**Comment by adler-j** [comment]
That does look like a reasonable release schedule. For 1.0 we want tensor valued discrete lp as well as a cuda backend.

**Comment by kohr-h** [comment]
I'll go ahead with this.

**Comment by kohr-h** [comment]
Done.

**Comment by adler-j** [comment]
Freaking tremendous and "done" does not sufficiently convey the success :) Now lets put our aims towards a proper 1.0 release (and getting an article out as well).

Btw, what happened to: https://github.com/odlgroup/odl/pull/1432

**Comment by kohr-h** [comment]
> Btw, what happened to: #1432

That'll go in as a regular PR on `master`, tonight if it gets approval in time :wink: 
I'll copy over the "highlights" from the release page.
