### ISSUE TITLE
Metaissue: Add datasets

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#997]
We should add the following datasets to the ODL datasets

- [ ] Mayo clinic data
- [ ] Elekta CBCT data (both Icon and XVI)
- [x] SOME open MRI dataset
- [ ] SOME open electron tomography dataset
- [ ] SOME syncrotron dataset

More suggestions are more than welcome!

**Comment by ozanoktem** [comment]
There are a number of x-ray phase contrast and TEM phase contrast data, both simulated and experimental. Would be nice to include those as well.

**Comment by kohr-h** [comment]
[Here's](http://www.aylward.org/notes/open-access-medical-image-repositories) a rather long list of medical data sources, but I expect that every one has some kind of data usage agreement that needs to be signed before getting the data.
For X-ray synchrotron data there is the [tomobank](https://github.com/tomography/tomobank). Access is through the Globus network, so no direct link there either. But I think it wouldn't be a problem to download and host one dataset somewhere.

**Comment by adler-j** [comment]
#1041 adds multi-channel MRI data from TU Graz.

**Comment by adler-j** [comment]
This is in a sense a perpetual issue. The framework is in place, closing.
